django_app/config/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^post/', include('post.urls')),
    url(r'^member/', include('member.urls')),
]

urlpatterns += static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

django_app/member/urls.py
from django.conf.urls import url

urlpatterns = [

]

django_app/mysite/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

django_app/post/urls.py
from django.conf.urls import url

from . import views

app_name = 'post'
urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^(?P<post_pk>\d+)/modify', views.post_modify, name='post_modify'),
    url(r'^(?P<post_pk>\d+)/delete', views.post_delete, name='post_delete'),

]

django_app/member/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    nickname = models.CharField(max_length=24, null=True, unique=True)

    def __str__(self):
        return self.nickname or self.username

django_app/post/models.py
from django.conf import settings
from django.db import models


class Post(models.Model):
    author = settings.AUTH_USER_MODEL
    photo = models.ImageField(
        upload_to='post',
        blank=True,
        null=True,
    )
    comment = models.CharField(max_length=100)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now_add=True)

django_app/post/forms/post.py
from django import forms

from ..models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'photo',
            'comment',
        ]

django_app/member/views.py
from django.shortcuts import render

# Create your views here.

django_app/post/views.py
from django.shortcuts import render, get_object_or_404, redirect

from .forms import PostForm
from .models import Post


def post_list(request):
    posts = Post.objects.all()

    context = {
        'posts': posts,
    }
    return render(request, 'post/post_list.html', context)


def post_modify(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
        return redirect('post:post_list')
    else:
        form = PostForm()

    context = {
        'post': post,
        'form': form,
    }
    return render(request, 'post/post_modify.html', context)


def post_delete(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    post.delete()
    return redirect('post:post_list')

django_app/templates/common/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

{% block content %}
{% endblock %}

</body>
</html>

django_app/templates/include/post.html
{% load static %}
<article>
    <header>
        <div>
            <span>{{ post.author }}</span>
        </div>
    </header>
    <div class="container">
        <a href="">
            <img width="400px" height="auto" src="{{ post.photo.url }}" alt="">
        </a>
    </div>
    <div>{{ post.comment }}</div>
    <div>{{ post.created_date }}</div>
    <div>
        <div style="float: left; margin: 0 5px 0 0;"><a href="{% url 'post:post_modify' post_pk=post.pk %}">
            <button>수정하기</button>
        </a></div>
        <div style="float: left; margin: 0 5px 0 0;"><a href="{% url 'post:post_delete' post_pk=post.pk %}">
            <button>삭제하기</button>
        </a></div>
    </div>
    <br><br>
</article>

django_app/templates/post/post_list.html
{% extends 'common/base.html' %}

{% block content %}
    {% for post in posts %}
        {% include 'include/post.html' %}
    {% endfor %}
{% endblock %}

django_app/templates/post/post_modify.html
{% extends 'common/base.html' %}

{% block content %}
    <div><h2>포스트 수정하기</h2></div>
    <div><img src="{{ post.photo.url }}" alt=""></div>
    <div>{{ post.comment }}</div>
    <br>
    <div>
        <form action="{% url 'post:post_modify' post_pk=post.pk %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div>{{ form }}</div>
            <button type="submit">수정하기</button>
        </form>
    </div>
{% endblock %}